# Configuration for episode tree visualization

object:
  width: 100
  height: 100
  text_size: 14
  text_margin: -150
  rounding_size: 10
  max_chars_per_line: 8

receptacle:
  horizontal_margin: 5
  target_height: 500
  object_margin: 60

room:
  min_width: 450
  min_height: 700
  horizontal_margin: 10
  vertical_margin: 10
  top_pad: 100
  bottom_pad: 175
  left_pad: 20
  right_pad: 20
  text_size: 14
  box_alpha: 1.0
  max_chars_per_line: 13

scene:
  target_width: 6000

